"use client";

import { useState, useEffect, useCallback } from "react";
import { createClient } from "@/lib/supabase/client";
import { useAuth } from "@/components/auth/auth-provider";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { X, CheckCircle2 } from "lucide-react";

/* ─── Types ──────────────────────────────────────────── */

interface SampleInfo {
  quality_id: string;
  color_code_id: string;
  dimension_id: string;
  qualityName: string;
  colorName: string;
  dimensionName: string;
}

interface FinishingModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  sample: SampleInfo;
  shortage?: number;
  onResolved: () => void;
}

/* ─── Component ──────────────────────────────────────── */

export function FinishingModal({
  open,
  onOpenChange,
  sample,
  shortage,
  onResolved,
}: FinishingModalProps) {
  const supabase = createClient();
  const { user } = useAuth();

  const [quantity, setQuantity] = useState(shortage ?? 1);
  const [finishingTypeId, setFinishingTypeId] = useState<string | null>(null);
  const [locationCode, setLocationCode] = useState("");

  const [booking, setBooking] = useState(false);
  const [error, setError] = useState("");

  const loadData = useCallback(async () => {
    const { data: rules } = await supabase
      .from("quality_finishing_rules")
      .select("finishing_type_id")
      .eq("quality_id", sample.quality_id)
      .eq("is_allowed", true)
      .limit(1);

    // Auto-select finishing type: use quality rule, or fall back to first active type
    let ftId = rules?.[0]?.finishing_type_id ?? null;
    if (!ftId) {
      const { data: types } = await supabase
        .from("finishing_types")
        .select("id")
        .eq("active", true)
        .limit(1);
      ftId = types?.[0]?.id ?? null;
    }
    setFinishingTypeId(ftId);
  }, [supabase, sample.quality_id]);

  useEffect(() => {
    if (open) {
      setQuantity(shortage ?? 1);
      setLocationCode("");
      setError("");
      loadData();
    }
  }, [open, shortage, loadData]);

  // Parse location code like "A1" → aisle="A", rack="1", level="1"
  function parseLocationCode(code: string): { aisle: string; rack: string; level: string } | null {
    const trimmed = code.trim().toUpperCase();
    if (!trimmed) return null;
    const match = trimmed.match(/^([A-Z])(\d)$/);
    if (!match) return null;
    return { aisle: match[1], rack: match[2], level: "1" };
  }

  // Find or create location by code
  async function resolveLocationId(): Promise<string | null> {
    const parsed = parseLocationCode(locationCode);
    if (!parsed) return null;

    // Try to find existing location
    const { data: existing } = await supabase
      .from("locations")
      .select("id")
      .eq("aisle", parsed.aisle)
      .eq("rack", parsed.rack)
      .eq("level", parsed.level)
      .limit(1);

    if (existing && existing.length > 0) return existing[0].id;

    // Create new location (label is auto-generated by the database)
    const { data: created, error: err } = await supabase
      .from("locations")
      .insert({ aisle: parsed.aisle, rack: parsed.rack, level: parsed.level })
      .select("id")
      .single();

    if (err) throw new Error(`Locatie aanmaken mislukt: ${err.message}`);
    return created.id;
  }

  async function handleBook() {
    if (!finishingTypeId || !user) return;
    setBooking(true);
    setError("");

    try {
      // Resolve location (optional)
      let locationId: string | null = null;
      if (locationCode.trim()) {
        const parsed = parseLocationCode(locationCode);
        if (!parsed) {
          setError("Ongeldige locatie. Gebruik een letter + cijfer, bijv. A1, B3");
          setBooking(false);
          return;
        }
        locationId = await resolveLocationId();
      }

      // If no location provided, use or create a default "ONBEKEND" location
      if (!locationId) {
        const { data: defaultLoc } = await supabase
          .from("locations")
          .select("id")
          .eq("aisle", "-")
          .eq("rack", "-")
          .eq("level", "-")
          .limit(1);

        if (defaultLoc && defaultLoc.length > 0) {
          locationId = defaultLoc[0].id;
        } else {
          const { data: created, error: err } = await supabase
            .from("locations")
            .insert({ aisle: "-", rack: "-", level: "-" })
            .select("id")
            .single();
          if (err) throw new Error(`Default locatie aanmaken mislukt: ${err.message}`);
          locationId = created.id;
        }
      }

      // Direct update finished_stock (bypass raw_stock trigger check)
      // First check if row exists
      const { data: existing } = await supabase
        .from("finished_stock")
        .select("quantity")
        .eq("quality_id", sample.quality_id)
        .eq("color_code_id", sample.color_code_id)
        .eq("dimension_id", sample.dimension_id)
        .eq("finishing_type_id", finishingTypeId)
        .eq("location_id", locationId)
        .maybeSingle();

      if (existing) {
        // Update existing row
        const { error: err } = await supabase
          .from("finished_stock")
          .update({ quantity: existing.quantity + quantity })
          .eq("quality_id", sample.quality_id)
          .eq("color_code_id", sample.color_code_id)
          .eq("dimension_id", sample.dimension_id)
          .eq("finishing_type_id", finishingTypeId)
          .eq("location_id", locationId);
        if (err) throw err;
      } else {
        // Insert new row
        const { error: err } = await supabase
          .from("finished_stock")
          .insert({
            quality_id: sample.quality_id,
            color_code_id: sample.color_code_id,
            dimension_id: sample.dimension_id,
            finishing_type_id: finishingTypeId,
            location_id: locationId,
            quantity,
          });
        if (err) throw err;
      }

      onResolved();
      onOpenChange(false);
    } catch (err: any) {
      setError(err.message ?? "Fout bij boeken");
    } finally {
      setBooking(false);
    }
  }

  if (!open) return null;

  const parsedLoc = parseLocationCode(locationCode);
  const locationValid = !locationCode.trim() || !!parsedLoc;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div
        className="absolute inset-0 bg-black/20 backdrop-blur-sm"
        onClick={() => onOpenChange(false)}
      />
      <div className="relative z-10 w-full max-w-md rounded-2xl bg-background p-6 ring-1 ring-border shadow-xl">
        {/* Header */}
        <div className="mb-5 flex items-center justify-between">
          <h2 className="text-lg font-semibold text-foreground">Afwerken boeken</h2>
          <button
            onClick={() => onOpenChange(false)}
            className="rounded-lg p-1 text-muted-foreground hover:bg-muted"
          >
            <X size={18} />
          </button>
        </div>

        {/* Sample info */}
        <div className="mb-5 rounded-lg bg-muted/50 p-3">
          <div className="font-medium text-card-foreground">
            {sample.qualityName} — {sample.colorName}
          </div>
          <div className="text-xs text-muted-foreground">{sample.dimensionName}</div>
          {shortage != null && (
            <div className="mt-1 text-sm text-red-600 font-semibold">
              Tekort: {shortage}
            </div>
          )}
        </div>

        {/* Quantity */}
        <div className="mb-5">
          <Label className="text-sm font-medium">Aantal</Label>
          <Input
            type="number"
            min={1}
            value={quantity}
            onChange={(e) => setQuantity(Math.max(1, Number(e.target.value)))}
            className="mt-2 w-28"
          />
        </div>

        {/* Location — simple code */}
        <div className="mb-5">
          <Label className="text-sm font-medium">
            Locatie <span className="font-normal text-muted-foreground">(optioneel)</span>
          </Label>
          <div className="mt-2 flex items-center gap-3">
            <Input
              value={locationCode}
              onChange={(e) => setLocationCode(e.target.value.toUpperCase().slice(0, 2))}
              placeholder="bijv. A1"
              className={`w-24 text-center font-mono text-lg uppercase ${
                !locationValid ? "border-red-400 focus:ring-red-400" : ""
              }`}
              maxLength={2}
            />
            {locationCode.trim() && (
              locationValid ? (
                <span className="text-xs text-green-600">
                  Gang {parsedLoc!.aisle}, Rek {parsedLoc!.rack}
                </span>
              ) : (
                <span className="text-xs text-red-600">
                  Gebruik letter + cijfer (A1, B3, ...)
                </span>
              )
            )}
          </div>
        </div>

        {error && <p className="mb-4 text-sm text-red-600">{error}</p>}

        {/* Actions */}
        <div className="flex justify-end gap-2">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Annuleren
          </Button>
          <Button
            onClick={handleBook}
            disabled={!finishingTypeId || !locationValid || booking}
            className="bg-green-600 text-white hover:bg-green-700"
          >
            <CheckCircle2 size={14} />
            {booking ? "Boeken..." : "Afwerken boeken"}
          </Button>
        </div>
      </div>
    </div>
  );
}
